name: controle_qualite
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.9+9

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  platform: ^3.1.0
  cupertino_icons: ^1.0.0
  http: ^0.13.0
  fluttertoast: ^7.1.6
  google_fonts: ^3.0.1
  animations: ^1.1.2
  simple_animations: ^1.3.3
  image_picker: ^0.8.3
  flutter_spinkit: "^4.1.2"
  flutter_windowmanager: ^0.2.0
  hive: ^2.0.3
  path_provider: ^2.0.11
  hive_flutter: ^1.0.0
  clipboard_listener: ^2.0.0
  ota_update: ^4.0.1
  package_info_plus: ^1.0.6
  encrypt: ^5.0.1
  flutter_udid: ^2.0.0
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"


flutter:
  assets:
      - assets/images/

  uses-material-design: true

